### ISSUE TITLE
SplitView: shownDisplayMode and hiddenDisplayMode doesn't work

### ISSUE THREAD

**Issue by kollster** [winjs/angular-winjs#15]
It seems that you cannot set the properties shownDisplayMode and hiddenDisplayMode in the html markup of the SplpitView directive. The two properties should map to the html attributes shown-display-mode and hidden-display-mode, but the properties are not set.

In the code example below, one would expect that shownDisplayMode would be set to "inline" and hiddenDisplayMode to "inline", but that is not the case - the properties are left with their default values.

```html
<win-split-view pane-hidden="false" shown-display-mode="inline" hidden-display-mode="inline">
    <win-split-view-pane>SplitView Navigation Pane</win-split-view-pane>
    <win-split-view-content>
        SplitView Content Area
    </win-split-view-content>
</win-split-view>
```

**Comment by AmazingJaze** [comment]
Thanks for the bug. Can you tell us which version of WinJS you are using? The angular-winjs project is currently configured for the [WinJS 4.0 preview](http://try.buildwinjs.com/#get:preview)  snapshot of WinJS. 

There have recently been some breaking API changes to Splitview, AppBar, ToolBar, and NavBar in the WinJS master branch that have not yet propagated into angular-winjs or the samples at [try.buildwinjs.com](http://try.buildwinjs.com). 

The majority of incoming API changes involve updating the nomenclature away from "shown" and "hidden" to "opened" and "closed" in order to more accurately match the functionality of these control as their design has changed over time.
https://github.com/winjs/winjs/blob/master/src/js/WinJS/Controls/SplitView/_SplitView.ts#L76-L94

**Comment by kollster** [comment]
I am using the bower package `winjs#release/4.0.0-preview` as mentioned on http://try.buildwinjs.com/#get:preview . Is there any workaround or should we wait for `angular-winjs` to get updated?

**Comment by rigdern** [comment]
`winjs#release/4.0.0-preview` and the current `angular-winjs` release work together.

I believe the problem with your snippet is that the usages of `inline` need to be quoted so that they are treated as strings. Like this:

```html
<win-split-view pane-hidden="false" shown-display-mode="'inline'" hidden-display-mode="'inline'">
```

Notice the extra single quotes around `inline`.

Let us know if that helps.

**Comment by kollster** [comment]
Thanks for the help. I missed the extra single quotes - after adding them, it works as expected. It would be nice though, if an error was thrown when trying to set an invalid value, instead of failing silently.
