### ISSUE TITLE
winPivot inside a split view

### ISSUE THREAD

**Issue by osmanm** [winjs/angular-winjs#44]
having a win-split-view and inserting win-pivot does not show content. 
you can not see..

"Pivots are useful for varied content" or other text.

![capture](https://cloud.githubusercontent.com/assets/2213350/8463472/818f5846-2008-11e5-8f80-c51f402f8fc7.PNG)

**Comment by jayrenn** [comment]
Hi @osmanm, try setting your Pivot to have a height of 100%. Let me know if that fixes your problem.

**Comment by osmanm** [comment]
100% height does not work. actually % does not work. vh works. :) thank you for your help. I set the height to 100vh. It worked as expected. not sure why I have to set the height though.

**Comment by rigdern** [comment]
This looks like a bug in the angular-winjs `winSplitViewContent` directive. Here's some code which you can use in an angular-winjs sample on the Try Site to repro the bug:

```js
// JavaScript

angular.module('sample', ['winjs']).controller("sampleController", function ($scope) {
});
```

```html
<!-- HTML -->

<div ng-app="sample" ng-controller="sampleController" style="height: 100%">
    <win-split-view>
        <win-split-view-pane>
            Pane
        </win-split-view-pane>
        <win-split-view-content>
            <div style="height: 100%; background-color: steelblue;">
                My blue background should be as tall as the SplitView
            </div>
        </win-split-view-content>
    </win-split-view>
</div>
```

The problem is that angular-winjs generates an extra element which is a child of `win-splitview-content`. The element has the class name `ng-scope`. The problem is that this extra element's height is size to content and all of your content appears inside of it. Consequently, percentage heights on your content do not work which is why the Pivot ends up being very short.

![image](https://cloud.githubusercontent.com/assets/199935/8587518/06813b74-25b2-11e5-89b2-676b4d4a456c.png)

The `winSplitViewPane` directive has the same problem.

**Comment by frenchyjef** [comment]
Hi,

Facing the same issue with a ListView inside a SplitView where the ListView data is only displaying the first item in the list and empty for all other items. If I resize the browser, all items will magically show up.   
(Note: this problem occurs for all browsers except latest version of Edge.)

I applied the workaround suggested above and it seems to work if I add a class with 'height:100%' to every single element starting from the body all the way down to the ListView element.

Thanks,
J-F

**Comment by frenchyjef** [comment]
Same issue with ListView inside a HubSection. However, even by putting height:100% everywhere, it does not fix the problem. 

Again, if I resize the browser, all items will magically show up.
(Note: this problem occurs for all browsers except latest version of Edge.)

Thanks,
J-F

**Comment by shafeeq116** [comment]
Hi

I was also facing same issue and found that PivotItem is not rendering. 
I changed the following line

    exists("PivotItem") && module.directive("winPivotItem", function () {

to 

    exists("Pivot") && module.directive("winPivotItem", function () {

and still it was not rendered. When used ng-repeat for listing pivot items, it started rendering. 

      <win-pivot>
            <win-pivot-item ng-repeat="item_pivot in app.items" header="item_pivot.title">
                   {{item_pivot.title}}
            </win-pivot-item>                        
      </win-pivot>

But due to styling issues, it was not shown inside splitView. Changed some style also

      <style>
        .win-pivot-header {
            color: #FFF !important;
        }
        .win-pivot-item {
            position:static !important;
        }
      </style>

and now pivot Items started displaying inside splitView.
